Fix start_pods script when env vars are missing
ansible/pinakes pull request #448
Opened 2022-03-29 19:07 UTC by mkanoor

If the env_vars is missing the script doesn't exist, it creates
an incomplete env which needs to be cleaned up.

If we leave the set -o nounset and the env var is missing the error
generated is not user friendly

./tools/minikube/scripts/start_pods.sh: line 11: PINAKES_CONTROLLER_URL: unbound variable

2022-03-29 21:26 UTC, hsong-rh commented
If `PINAKES_CONTROLLER_VERIFY_SSL` is not exported, its default value will be empty string, which will cause source refresh cronjob failed:
```
2022-03-29 21:00:04,612 — rq.worker — ERROR — Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.9/site-packages/rq/worker.py", line 1061, in perform_job
    rv = job.perform()
  File "/opt/app-root/lib64/python3.9/site-packages/rq/job.py", line 821, in perform
    self._result = self._execute()
  File "/opt/app-root/lib64/python3.9/site-packages/rq/job.py", line 844, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/opt/app-root/src/pinakes/main/inventory/tasks.py", line 29, in refresh_all_sources
    refresh_task(source.tenant_id, source.id)
  File "/opt/app-root/src/pinakes/main/inventory/tasks.py", line 35, in refresh_task
    svc = CheckSourceAvailability(source_id)
  File "/opt/app-root/src/pinakes/main/inventory/task_utils/check_source_availability.py", line 23, in __init__
    self.tower = TowerAPI()
  File "/opt/app-root/src/pinakes/main/inventory/task_utils/tower_api.py", line 34, in __init__
    self.verify_ssl = bool(strtobool(verify_ssl))
  File "/usr/lib64/python3.9/distutils/util.py", line 320, in strtobool
    raise ValueError("invalid truth value %r" % (val,))
ValueError: invalid truth value ''
```

2022-03-30 14:41 UTC, cutwater requested changes
@mkanoor

1. Please always use `set -o nounset` (or `set -u`) in bash scripts, as it prevents accidentally using undefined variables, which may be harmful.
2. Using mandatory environment variables is not user friendly either, as it requires to configure these variables even if there is no controller present in the environment.

2022-03-30 16:13 UTC, cutwater requested changes
@mkanoor Update to my previos comment. As we discussed with @eclarizio, we want to keep those variables mandatory and provide another script to setup development environment without controller, for local development purposes.

In order to achieve this you don't  need to remove `set -o nounset` and default assignments, you can keep the lines I marked and only change the if condition behavior.

2022-03-30 16:13 UTC, cutwater commented on tools/minikube/scripts/start_pods.sh
> -set -o nounset
Keep this line.

2022-03-30 16:13 UTC, cutwater commented on tools/minikube/scripts/start_pods.sh
> -PINAKES_CONTROLLER_VERIFY_SSL=${PINAKES_CONTROLLER_VERIFY_SSL:-}
Keep these lines.

2022-03-30 16:22 UTC, eclarizio reviewed
As @cutwater mentioned, we discussed having a separate `start_pods_dev.sh` (or whatever other name we want to have) for not requiring the controller environment variables, and that's probably the best way to go for any user who may want to contribute to the codebase and be able to run the tests or make simple API calls. That can be done in a separate PR.

For this one, I think if we can keep the `set -o nounset` and the setting of the defaults while ensuring the error messages are user friendly and it exits if they aren't set, that would be ideal.

2022-03-30 17:14 UTC, mkanoor commented
@cutwater @eclarizio Please review

2022-03-30 17:59 UTC, eclarizio approved these changes

2022-03-30 18:20 UTC, hsong-rh approved these changes
With these changes I got expected error message and stopped deployment when env variable is not exported.

2022-03-30 18:52 UTC, merged