[SSP-2927] Added customized UniqueTogetherValidators
ansible/pinakes pull request #518
Opened 2022-05-12 20:56 UTC by bzwei

https://issues.redhat.com/browse/SSP-2927

When a UniqueConstraint is added to a model it does not automatically trigger the corresponding DRF validator. If there is a violation a 500 error is raised by underlying database instead of 400 error by the validator.

The default UniqueTogetherValidator cannot be directly applied because the post body does not contain tenant field. Two customized validators are added for this purpose.

Also adjust the length limit of the name field in OrderItem because the name is a copy from PortfolioItem. The limits must be equal. This is a followup to #499

2022-05-13 09:47 UTC, cutwater requested changes
_deleted_

2022-05-13 10:32 UTC, cutwater requested changes
The whole idea of a preliminary validation of a unique constraints is at least questionable. It doesn't prevent unique constraint violation from happening, just makes it occurrence more rare (limited to race conditions that will eventually occur but will be hard to debug), creating an illusion of properly working system.

I think the problem linked in the description should be addressed first by appropriate handling of database integrity errors rather than preliminary validation.

2022-05-13 14:12 UTC, bzwei commented
@cutwater DRF validations occur all the time, for example the char field max length validation is automatically checked. What is done by this PR is to include a missing unique validator during the validation process. We could have used the `unique-together` option, then `UniqueTogetherValidator` will be automatically triggered. We however choose to use `UniqueConstraint` because `unique-together` is no longer recommended according to https://docs.djangoproject.com/en/dev/ref/models/options/#unique-together. I think enabling a unique validator is still appropriate.

Properly handling integrity errors raised by database is helpful in general but it can be another story. The reported issue is clearly a user error, not caused by other reasons such as race condition. I thought of catching integrity errors in our customized drf exception_handler, but it cannot distinguish whether the error is caused by user input or our internal logic. A validator is still proper to address the user error.

2022-05-16 10:51 UTC, mkanoor commented on pinakes/main/migrations/0048_remove_notificationtype_main_notificationtype_n_type_unique_and_more.py
> +# Generated by Django 4.0.2 on 2022-05-12 20:35
@bzwei You might want to redo this migration since a recent migration change got merged

2022-05-16 11:57 UTC, cutwater commented
> DRF validations occur all the time, for example the char field max length validation is automatically checked.

Indeed validations occur all the time, but there is an important difference between validation of an input data (e.g. max length) and unique constraint failures: the latter one depends on a system state and cannot be reliably validated in advance unless locking the entire table. The preliminary validation of existence of a record in the database creates a race condition. While it is still safe, due to unique constraint existence, is there any particular reason for splitting the logic into two pieces that do the same job?

2022-05-18 20:21 UTC, bzwei commented
@cutwater Per our discussion, I added a processing for IntegrityError in exception_handler.

2022-05-19 13:52 UTC, cutwater approved these changes
Minor comments, otherwise LGTM

2022-05-24 08:40 UTC, cutwater approved these changes

2022-05-24 18:07 UTC, eclarizio approved these changes

2022-05-25 06:14 UTC, merged